# Generated by Django 5.2 on 2025-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_img.jpg', null=True, upload_to='event_asset'),
        ),
    ]
