# Generated by Django 5.2 on 2025-04-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_img.jpeg', null=True, upload_to='event_asset'),
        ),
    ]
