# Generated by Django 5.2 on 2025-04-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=models.ImageField(blank=True, default='event_asset/default_img.jpg', null=True, upload_to='event_asset'),
        ),
    ]
