# Generated by Django 5.2 on 2025-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_blogpost_offer_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
